services:
  cuda-sim:
    build:
      context: .
      dockerfile: Dockerfile
    image: gpu-assignment:latest
    container_name: gpu_heat_diffusion
    working_dir: /workspace
    volumes:
      - ./:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    command: ["./heat_diffusion", "256", "1e-4", "2000000"]
